apiVersion: v1
data:
  app.py: "#!/usr/bin/env python3\r\n\"\"\"\r\nSSE Bridge Worker - Adds x-stream-filter-value
    header to events for the API.\r\n\r\nThe NLdoc API expects events in the 'results'
    stream with an 'x-stream-filter-value'\r\nheader containing the document ID. The
    stations publish events to 'specs.{docId}'\r\nbut without this header, so the
    API cannot filter them correctly.\r\n\r\nThis bridge:\r\n1. Consumes events from
    specs.* on nldoc.topics\r\n2. Adds the x-stream-filter-value header with the document
    ID\r\n3. Republishes to the 'results' exchange (which feeds the stream)\r\n\"\"\"\r\n\r\nimport
    os\r\nimport sys\r\nimport json\r\nimport time\r\nimport pika\r\n\r\n# Force unbuffered
    output\r\nsys.stdout.reconfigure(line_buffering=True)\r\nsys.stderr.reconfigure(line_buffering=True)\r\n\r\ndef
    log(msg):\r\n    print(f\"[sse-bridge] {msg}\", flush=True)\r\n\r\nAMQP_HOST =
    os.environ.get(\"AMQP_HOST\", \"localhost\")\r\nAMQP_PORT = int(os.environ.get(\"AMQP_PORT\",
    \"5672\"))\r\nAMQP_USERNAME = os.environ.get(\"AMQP_USERNAME\", os.environ.get(\"RABBITMQ_DEFAULT_USER\",
    \"guest\"))\r\nAMQP_PASSWORD = os.environ.get(\"AMQP_PASSWORD\", os.environ.get(\"RABBITMQ_DEFAULT_PASS\",
    \"guest\"))\r\n\r\n\r\ndef extract_document_id(routing_key, payload):\r\n    \"\"\"Extract
    document ID from routing key or payload.\"\"\"\r\n    # specs.{document_id}\r\n
    \   if routing_key.startswith(\"specs.\"):\r\n        return routing_key.split(\".\",
    1)[1]\r\n    \r\n    # documents.{document_id}\r\n    if routing_key.startswith(\"documents.\"):\r\n
    \       return routing_key.split(\".\", 1)[1]\r\n\r\n    # events.{document_id}
    (custom event topic for SSE to avoid station-document-source parsing)\r\n    if
    routing_key.startswith(\"events.\"):\r\n        return routing_key.split(\".\",
    1)[1]\r\n    \r\n    # Try from payload\r\n    if isinstance(payload, dict):\r\n
    \       if \"documentId\" in payload:\r\n            return payload[\"documentId\"]\r\n
    \       if \"_documentId\" in payload:\r\n            return payload[\"_documentId\"]\r\n
    \       if \"context\" in payload and \"documentId\" in payload[\"context\"]:\r\n
    \           return payload[\"context\"][\"documentId\"]\r\n    \r\n    return
    None\r\n\r\n\r\ndef main():\r\n    log(\"Starting SSE Bridge Worker\")\r\n    log(f\"Connecting
    to {AMQP_HOST}:{AMQP_PORT}\")\r\n    \r\n    credentials = pika.PlainCredentials(AMQP_USERNAME,
    AMQP_PASSWORD)\r\n    \r\n    while True:\r\n        try:\r\n            connection
    = pika.BlockingConnection(\r\n                pika.ConnectionParameters(\r\n                    host=AMQP_HOST,\r\n
    \                   port=AMQP_PORT,\r\n                    credentials=credentials,\r\n
    \                   heartbeat=30\r\n                )\r\n            )\r\n            channel
    = connection.channel()\r\n            \r\n            # Declare the bridge queue\r\n
    \           queue_name = \"sse-bridge-queue\"\r\n            channel.queue_declare(queue=queue_name,
    durable=True)\r\n            \r\n            # Bind to specs.* and documents.*
    events\r\n            channel.queue_bind(\r\n                queue=queue_name,\r\n
    \               exchange=\"nldoc.topics\",\r\n                routing_key=\"specs.*\"\r\n
    \           )\r\n            channel.queue_bind(\r\n                queue=queue_name,\r\n
    \               exchange=\"nldoc.topics\",\r\n                routing_key=\"documents.*\"\r\n
    \           )\r\n            channel.queue_bind(\r\n                queue=queue_name,\r\n
    \               exchange=\"nldoc.topics\",\r\n                routing_key=\"events.*\"\r\n
    \           )\r\n            \r\n            log(f\"Consuming from {queue_name}
    (specs.* , documents.* , events.*)\")\r\n            log(\"Bridging events to
    'results' exchange with x-stream-filter-value header\")\r\n            \r\n            def
    handle_event(ch, method, properties, body):\r\n                routing_key = method.routing_key\r\n
    \               \r\n                try:\r\n                    payload = json.loads(body.decode(\"utf-8\"))\r\n
    \               except:\r\n                    payload = {}\r\n                \r\n
    \               # Extract document ID\r\n                doc_id = extract_document_id(routing_key,
    payload)\r\n                \r\n                if not doc_id:\r\n                    log(f\"Could
    not extract doc ID from {routing_key}\")\r\n                    ch.basic_ack(delivery_tag=method.delivery_tag)\r\n
    \                   return\r\n                \r\n                # Get existing
    headers\r\n                headers = dict(properties.headers) if properties.headers
    else {}\r\n                \r\n                # Add the stream filter header\r\n
    \               headers[\"x-stream-filter-value\"] = doc_id\r\n                \r\n
    \               # Log the bridge\r\n                event_type = payload.get(\"type\",
    \"unknown\")\r\n                log(f\"Bridging {routing_key} -> results | doc={doc_id}
    | type={event_type}\")\r\n                \r\n                # Republish to results
    exchange (which feeds the stream)\r\n                ch.basic_publish(\r\n                    exchange=\"results\",\r\n
    \                   routing_key=\"\",  # Fanout exchange ignores routing key\r\n
    \                   body=body,\r\n                    properties=pika.BasicProperties(\r\n
    \                       content_type=properties.content_type,\r\n                        content_encoding=properties.content_encoding,\r\n
    \                       headers=headers,\r\n                        delivery_mode=2\r\n
    \                   )\r\n                )\r\n                \r\n                ch.basic_ack(delivery_tag=method.delivery_tag)\r\n
    \           \r\n            channel.basic_qos(prefetch_count=10)\r\n            channel.basic_consume(queue=queue_name,
    on_message_callback=handle_event)\r\n            channel.start_consuming()\r\n
    \           \r\n        except pika.exceptions.AMQPConnectionError as e:\r\n            log(f\"Connection
    lost: {e}, reconnecting in 5s...\")\r\n            time.sleep(5)\r\n        except
    Exception as e:\r\n            log(f\"Error: {e}, retrying in 5s...\")\r\n            import
    traceback\r\n            traceback.print_exc()\r\n            time.sleep(5)\r\n\r\n\r\nif
    __name__ == \"__main__\":\r\n    main()\r\n\r\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: sse-bridge-code
