apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio
  namespace: nldoc
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/instance: minio
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 20Gi

