apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnativepg
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
    argocd.argoproj.io/sync-options: CreateNamespace=true
spec:
  project: nldoc
  source:
    repoURL: https://cloudnative-pg.github.io/charts
    chart: cloudnative-pg
    targetRevision: 0.22.0
    helm:
      values: |
        nodeSelector:
          role: prod-data
        tolerations:
          - key: "db-only"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
