apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: nldoc
  namespace: argocd
spec:
  description: NLDoc project
  destinations:
    - namespace: nldoc
      server: https://kubernetes.default.svc
    - namespace: cnpg-system
      server: https://kubernetes.default.svc
    - namespace: rabbitmq-system
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://gitlab.com/logius/nldoc/getting-started.git
    - https://cloudnative-pg.github.io/charts
    - https://github.com/ConductionNL/NL_doc.git
    - git@github.com:ConductionNL/gitops-postgres.git
    - https://gitlab.com/api/v4/projects/68736728/packages/helm/stable
    - https://gitlab.com/api/v4/projects/68643351/packages/helm/stable
    - https://gitlab.com/api/v4/projects/68640094/packages/helm/stable
    - https://charts.min.io
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
